# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-15 20:52
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApiJobUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('IP', 'In Progress'), ('SC', 'Success'), ('FL', 'Failure')], default='PN', max_length=2)),
                ('request_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('result_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Date last modified')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_core.ApiJob')),
            ],
        ),
    ]
