# Generated by Django 2.2.20 on 2022-11-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apijobunit',
            old_name='job',
            new_name='parent',
        ),
    ]
