# Generated by Django 2.2.20 on 2022-11-27 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0002_unit_rename_job_to_parent'),
        ('jobs', '0006_rename_to_result_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='apijobunit',
            name='internal_job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.Job'),
        ),
    ]
