# Generated by Django 2.2.20 on 2022-11-27 06:09

from django.db import migrations


def data_from_units_to_internal_jobs(apps, schema_editor):
    ApiJobUnit = apps.get_model('api_core', 'ApiJobUnit')
    Job = apps.get_model('jobs', 'Job')

    for unit in ApiJobUnit.objects.all():
        error_message = ''
        if unit.result_json and unit.result_json.get('errors'):
            error_message = unit.result_json['errors'][0]

        arg_identifier = (
            f"{unit.parent.pk},{unit.request_json['image_order'] + 1}")
        job = Job(
            job_name=unit.type,
            arg_identifier=arg_identifier,
            status=unit.status,
            error_message=error_message,
            scheduled_start_date=unit.create_date,
        )
        job.save()

        # Must set create date after creation since it's an auto-add-now
        # field.
        # Must set modify date with update() since it's an auto-now field.
        Job.objects.filter(pk=job.pk).update(
            create_date=unit.create_date, modify_date=unit.modify_date)

        unit.internal_job = job
        unit.save()


def data_from_internal_jobs_to_units(apps, schema_editor):
    ApiJobUnit = apps.get_model('api_core', 'ApiJobUnit')

    for unit in ApiJobUnit.objects.all():
        job = unit.internal_job
        unit.type = job.job_name
        unit.status = job.status
        unit.create_date = job.create_date
        unit.save()

        # Must set modify date with update() since it's an auto-now field.
        ApiJobUnit.objects.filter(pk=unit.pk).update(
            modify_date=job.modify_date)

        unit.internal_job.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0003_apijobunit_internal_job'),
    ]

    operations = [
        migrations.RunPython(
            data_from_units_to_internal_jobs,
            data_from_internal_jobs_to_units),
    ]
