# Generated by Django 2.2.20 on 2022-11-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0004_port_unit_data_to_internal_jobs'),
    ]

    operations = [
        # Add default so that field removal is reversible
        migrations.AlterField(
            model_name='apijobunit',
            name='type',
            field=models.CharField(max_length=30, default=''),
        ),
        # Remove fields
        migrations.RemoveField(
            model_name='apijobunit',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='apijobunit',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='apijobunit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='apijobunit',
            name='type',
        ),
        # Make non-null
        migrations.AlterField(
            model_name='apijobunit',
            name='internal_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='jobs.Job'),
        ),
    ]
