# Generated by Django 2.2.20 on 2022-11-28 01:25

from django.db import migrations


def order_from_request_json_to_field(apps, schema_editor):
    ApiJobUnit = apps.get_model('api_core', 'ApiJobUnit')

    for unit in ApiJobUnit.objects.all():
        unit.order_in_parent = unit.request_json['image_order'] + 1
        unit.save()


def order_from_field_to_request_json(apps, schema_editor):
    ApiJobUnit = apps.get_model('api_core', 'ApiJobUnit')

    for unit in ApiJobUnit.objects.all():
        unit.request_json['image_order'] = unit.order_in_parent - 1
        unit.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0006_apijobunit_order_in_parent'),
    ]

    operations = [
        migrations.RunPython(
            order_from_request_json_to_field,
            order_from_field_to_request_json),
    ]
