# Generated by Django 3.2.18 on 2023-04-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0008_unit_order_required_and_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apijobunit',
            name='request_json',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='apijobunit',
            name='result_json',
            field=models.JSONField(null=True),
        ),
    ]
