# Generated by Django 2.2.20 on 2022-11-25 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_squashed_0033_remove_image_annotation_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('arg_identifier', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('IP', 'In Progress'), ('DN', 'Done')], default='PN', max_length=2)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('attempt_number', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('scheduled_start_time', models.DateTimeField(verbose_name='Scheduled start time')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='Finish time')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Source')),
            ],
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(status='IP'), fields=('job_name', 'arg_identifier'), name='unique_running_jobs'),
        ),
    ]
