# Generated by Django 2.2.20 on 2022-11-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='finish_time',
        ),
        migrations.AddField(
            model_name='job',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Time modified'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('IP', 'In Progress'), ('SC', 'Success'), ('FL', 'Failure')], default='PN', max_length=2),
        ),
    ]
