# Generated by Django 2.2.20 on 2022-11-28 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_status_and_modify_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='scheduled_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Scheduled start time'),
        ),
    ]
