# Generated by Django 2.2.20 on 2022-11-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_scheduled_start_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='create_time',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='scheduled_start_time',
            new_name='scheduled_start_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='modify_time',
            new_name='modify_date',
        ),
    ]
