# Generated by Django 2.2.20 on 2022-11-28 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_times_to_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='job',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='job',
            name='scheduled_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Scheduled start date'),
        ),
    ]
