# Generated by Django 2.2.20 on 2022-12-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_rename_to_result_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='persist',
            field=models.BooleanField(default=False),
        ),
    ]
