# Generated by Django 4.1.8 on 2023-06-04 06:18

from django.db import migrations


def port_status_values(apps, port_spec):
    Job = apps.get_model('jobs', 'Job')

    for job in Job.objects.all():
        # Use update() so we can set the modify date to the existing value
        # rather than having it auto-set to the current date.
        Job.objects.filter(pk=job.pk).update(
            status=port_spec[job.status], modify_date=job.modify_date)


def port_status_values_forwards(apps, schema_editor):
    port_status_values(apps, dict(
        IP='in_progress',
        PN='pending',
        SC='success',
        FL='failure',
    ))


def port_status_values_backwards(apps, schema_editor):
    port_status_values(apps, dict(
        in_progress='IP',
        pending='PN',
        success='SC',
        failure='FL',
    ))


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_status_change_value_choices'),
    ]

    operations = [
        migrations.RunPython(
            port_status_values_forwards, port_status_values_backwards),
    ]
