# Generated by Django 4.1.8 on 2023-06-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_status_port_values'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='job',
            name='unique_running_jobs',
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('job_name', 'arg_identifier'), name='unique_running_jobs'),
        ),
    ]
