# Generated by Django 1.11.29 on 2021-04-13 23:26
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Dashed URL for the post. Example: officially-out-of-beta', max_length=80, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Post content will be interpreted as Markdown.')),
                ('preview_content', models.TextField(blank=True, help_text="Preview content shown on the list of blog posts. If left blank, a preview is generated automatically using the first part of the post's main content. Interpreted as Markdown.")),
                ('is_published', models.BooleanField(default=False)),
                ('published_timestamp', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'get_latest_by': 'published_timestamp',
            },
        ),
    ]
