# Generated by Django 1.11.23 on 2019-08-06 19:12
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('andablog', '0007_auto_20190315_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
            ],
            options={
                'get_latest_by': 'published_timestamp',
                'proxy': True,
                'indexes': [],
            },
            bases=('andablog.entry',),
        ),
    ]
