# Generated by Django 1.11.29 on 2021-04-10 09:21
from django.db import migrations


def entries_to_blogposts(apps, schema_editor):
    Entry = apps.get_model('blog', 'Entry')
    BlogPost = apps.get_model('blog', 'BlogPost')

    for entry in Entry.objects.all().order_by('pk'):
        # Port author from ForeignKey to CharField
        if entry.author:
            author = entry.author.first_name + " " + entry.author.last_name
        else:
            author = ""
        # Find/replace image paths
        content = entry.content.raw.replace(
            'andablog/images', 'article_images')
        preview_content = entry.preview_content.raw

        post = BlogPost(
            title=entry.title,
            slug=entry.slug,
            author=author,
            content=content,
            preview_content=preview_content,
            is_published=entry.is_published,
            published_timestamp=entry.published_timestamp,
        )
        post.save()


def blogposts_to_entries(apps, schema_editor):
    Entry = apps.get_model('blog', 'Entry')
    BlogPost = apps.get_model('blog', 'BlogPost')

    for post in BlogPost.objects.all().order_by('pk'):
        # Find/replace image paths
        content = post.content.replace('article_images', 'andablog/images')

        entry = Entry(
            title=post.title,
            slug=post.slug,
            content=content,
            is_published=post.is_published,
            published_timestamp=post.published_timestamp,
            author=None,
            preview_content=post.preview_content,
        )
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_blogpost'),
    ]

    operations = [
        migrations.RunPython(
            entries_to_blogposts, blogposts_to_entries, elidable=True),
    ]
