# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-12 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField()),
                ('source_name', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('user_username', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[(b'ml', b'ml'), (b'source', b'source'), (b'image', b'image'), (b'annotation', b'annotation'), (b'account', b'account')], max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.NewsItem')),
            ],
        ),
    ]
