# Generated by Django 1.11.29 on 2020-06-18 18:26
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='category',
            field=models.CharField(choices=[('ml', 'ml'), ('source', 'source'), ('image', 'image'), ('annotation', 'annotation'), ('account', 'account')], max_length=50),
        ),
    ]
