# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=128, null=True, verbose_name='Type')),
                ('info', models.TextField()),
                ('data', models.TextField(blank=True, null=True)),
                ('path', models.URLField(blank=True, null=True)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('html', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Error log',
                'verbose_name_plural': 'Error logs',
            },
        ),
    ]
