# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='latest_robot_annotator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Robot'),
        ),
        migrations.AlterField(
            model_name='image',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Metadata'),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='images.ImageStatus'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='value1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='images.Value1'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='value2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='images.Value2'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='value3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='images.Value3'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='value4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='images.Value4'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='value5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='images.Value5'),
        ),
        migrations.AlterField(
            model_name='source',
            name='labelset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annotations.LabelSet'),
        ),
    ]
