# Generated by Django 2.2.20 on 2021-05-08 05:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_squashed_0033_remove_image_annotation_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcifyRateTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('rates_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('region', models.CharField(blank=True, max_length=30)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Source')),
            ],
            options={
                'verbose_name': 'Calcification rate table',
            },
        ),
        migrations.AddConstraint(
            model_name='calcifyratetable',
            constraint=models.UniqueConstraint(fields=('source', 'name'), name='unique_name_within_source'),
        ),
    ]
