# Generated by Django 3.2.18 on 2023-04-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcifyratetable',
            name='rates_json',
            field=models.JSONField(),
        ),
    ]
