# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-31 03:46
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_language_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.AlterField(
            model_name='profile',
            name='mugshot',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text=b'Image to display in your profile.', upload_to=accounts.models.get_avatar_upload_path, verbose_name=b'Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[(b'open', b'Public'), (b'registered', b'Registered users only'), (b'closed', b'Private')], default=b'registered', help_text=b'Designates who can view your profile.', max_length=15, verbose_name=b'Privacy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
    ]
