# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-01 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_about_me_max_length_increase'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='affiliation',
            field=models.CharField(blank=True, help_text=b'Your university, research institution, etc.', max_length=100, verbose_name=b'Affiliation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='how_did_you_hear_about_us',
            field=models.CharField(blank=True, max_length=500, verbose_name=b'How did you hear about us?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_description',
            field=models.CharField(blank=True, max_length=500, verbose_name=b'Project description'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reason_for_registering',
            field=models.CharField(blank=True, max_length=500, verbose_name=b'Reason for registering'),
        ),
    ]
