# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-01 06:19
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_affiliation_and_other_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='random_gravatar_hash',
            field=models.CharField(default=accounts.models.get_random_gravatar_hash, editable=False, help_text=b"If an avatar isn't specified in another way, the fallback is a Gravatar based on this hash.", max_length=32, verbose_name=b'Random Gravatar hash'),
        ),
        migrations.AddField(
            model_name='profile',
            name='use_email_gravatar',
            field=models.BooleanField(default=False, help_text=b"If you're not sure what Gravatar is, just leave this unchecked.", verbose_name=b'Use a Gravatar based on my email address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mugshot',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text=b'Upload an image to display in your profile.', upload_to=accounts.models.get_avatar_upload_path, verbose_name=b'Avatar file'),
        ),
    ]
