# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-01 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_avatar_additions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mugshot',
            new_name='avatar_file',
        ),
    ]
