# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-19 01:54
from __future__ import unicode_literals

from django.db import migrations

from ..hashers import PBKDF2WrappedSHA1PasswordHasher


def forwards_func(apps, schema_editor):
    # Re-hash SHA1 hashes with the PBKDF2 algorithm for better security.
    User = apps.get_model('auth', 'User')
    users = User.objects.filter(password__startswith='sha1$')
    hasher = PBKDF2WrappedSHA1PasswordHasher()
    for user in users:
        algorithm, salt, sha1_hash = user.password.split('$', 2)
        user.password = hasher.encode_sha1_hash(sha1_hash, salt)
        user.save(update_fields=['password'])


def do_nothing(apps, schema_editor):
    # There isn't really a reverse operation that makes sense here.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_make_distinct_gravatar_hashes'),
        # Latest contrib.auth migration at time of this migration's creation
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.RunPython(forwards_func, do_nothing, elidable=True),
    ]
