# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 18:26
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_wrap_sha1_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.CharField(blank=True, max_length=1000, verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='affiliation',
            field=models.CharField(blank=True, help_text='Your university, research institution, etc.', max_length=100, verbose_name='Affiliation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_file',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Upload an image to display in your profile.', upload_to=accounts.models.get_avatar_upload_path, verbose_name='Avatar file'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='how_did_you_hear_about_us',
            field=models.CharField(blank=True, max_length=500, verbose_name='How did you hear about us?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[('open', 'Public'), ('registered', 'Registered users only'), ('closed', 'Private')], default='registered', help_text='Designates who can view your profile.', max_length=15, verbose_name='Privacy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='project_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Project description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='random_gravatar_hash',
            field=models.CharField(default=accounts.models.get_random_gravatar_hash, editable=False, help_text="If an avatar isn't specified in another way, the fallback is a Gravatar based on this hash.", max_length=32, verbose_name='Random Gravatar hash'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reason_for_registering',
            field=models.CharField(blank=True, max_length=500, verbose_name='Reason for registering'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='use_email_gravatar',
            field=models.BooleanField(default=False, help_text="If you're not sure what Gravatar is, just leave this unchecked.", verbose_name='Use a Gravatar based on my email address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
