# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-25 08:08
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('annotations', '0001_initial'), ('annotations', '0002_auto_20160415_1727'), ('annotations', '0003_add_empty_labelset'), ('annotations', '0004_alter_specify_on_delete'), ('annotations', '0005_remove_empty_labelset'), ('annotations', '0006_update_label_thumbnail_filepaths'), ('annotations', '0007_color_setting_typo_fix'), ('annotations', '0008_rename_vision_backend_fields'), ('annotations', '0009_rename_labelgroup_table'), ('annotations', '0010_alter_label_group_foreignkey'), ('annotations', '0011_delete_labelgroup'), ('annotations', '0012_rename_label_table'), ('annotations', '0013_alter_annotation_label_foreignkey'), ('annotations', '0014_delete_label'), ('annotations', '0015_rename_labelset_table'), ('annotations', '0016_delete_labelset'), ('annotations', '0017_tool_settings_one_to_one'), ('annotations', '0018_annotation_point_one_to_one'), ('annotations', '0019_field_string_attributes_to_unicode'), ('annotations', '0020_imageannotationinfo'), ('annotations', '0021_populate_imageannotationinfo')]

    initial = True

    dependencies = [
        ('images', '0001_squashed_0033_remove_image_annotation_progress'),
        ('labels', '0001_squashed_0012_field_string_attributes_to_unicode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vision_backend', '0001_squashed_0011_features_image_non_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_date', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labels.Label')),
                ('point', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='images.Point')),
                ('robot_version', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vision_backend.Classifier')),
                ('source', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='images.Source')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationToolAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
                ('source', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='images.Source')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationToolSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_marker', models.CharField(choices=[('crosshair', 'Crosshair'), ('circle', 'Circle'), ('crosshair and circle', 'Crosshair and circle'), ('box', 'Box')], default='crosshair', max_length=30)),
                ('point_marker_size', models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('point_marker_is_scaled', models.BooleanField(default=False)),
                ('point_number_size', models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('point_number_is_scaled', models.BooleanField(default=False)),
                ('unannotated_point_color', models.CharField(default='FFFF00', max_length=6, verbose_name='Not annotated point color')),
                ('robot_annotated_point_color', models.CharField(default='FFFF00', max_length=6, verbose_name='Unconfirmed point color')),
                ('human_annotated_point_color', models.CharField(default='8888FF', max_length=6, verbose_name='Confirmed point color')),
                ('selected_point_color', models.CharField(default='00FF00', max_length=6)),
                ('show_machine_annotations', models.BooleanField(default=True)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnnotationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('image', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='annoinfo', to='images.Image')),
                ('last_annotation', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='annotations.Annotation')),
            ],
        ),
    ]
