# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 01:43
from __future__ import unicode_literals

from django.db import migrations


def remove_empty_labelset(apps, schema_editor):
    LabelSet = apps.get_model('annotations', 'LabelSet')

    # Get the empty labelset.
    # Must match the former LabelSet.EMPTY_LABELSET_ID.
    # (Even if we hadn't removed that attribute, we couldn't have
    # accessed it directly from here anyway.)
    empty_labelset = LabelSet.objects.get(pk=-1)

    # Get the sources using the empty labelset.
    sources = empty_labelset.source_set.all()

    # For each of these sources, set the labelset field to null
    # (specified as None in Python).
    for source in sources:
        source.labelset = None
        source.save()

    # Delete the empty labelset.
    empty_labelset.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_alter_specify_on_delete'),
        ('images', '0003_alter_source_labelset_null'),
    ]

    operations = [
        migrations.RunPython(remove_empty_labelset, elidable=True),
    ]
