# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0007_color_setting_typo_fix'),
        ('vision_backend', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='robot_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vision_backend.Classifier'),
        ),
    ]
