# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0008_rename_vision_backend_fields'),
    ]

    # Add custom database_operations
    database_operations = [
        # You have to use Django's database table naming defaults to get the
        # name 'labels_labelgroup'. It is basically <app_name>_<model_name>.
        migrations.AlterModelTable('LabelGroup', 'labels_labelgroup'),
    ]

    # Don't modify the Django 'state' yet
    state_operations = [

    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]