# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0012_rename_label_table'),
        ('labels', '0002_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labels.Label'),
        ),
        migrations.AlterField(
            model_name='labelset',
            name='labels',
            field=models.ManyToManyField(to='labels.Label'),
        ),
    ]
