# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0014_delete_label'),
    ]

    # Add custom database_operations
    database_operations = [
        # You have to use Django's database table naming defaults to get the
        # name 'labels_labelset'. It is basically <app_name>_<model_name>.
        #
        # For ManyToMany, it's <table_name_of_model>_<m2m_field_name>,
        # but AlterModelTable takes care of this automatically.
        # https://code.djangoproject.com/ticket/23630
        migrations.AlterModelTable('LabelSet', 'labels_labelset'),
    ]

    # Don't modify the Django 'state' yet
    state_operations = [

    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
