# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0015_rename_labelset_table'),
        ('images', '0014_alter_source_labelset_foreignkey'),
    ]

    # This needs to be a state-only operation because the database model was
    # renamed, and no longer exists according to Django.
    state_operations = [
        migrations.DeleteModel(
            name='LabelSet',
        ),
    ]

    operations = [
        # After this state operation, the Django DB state should match the
        # actual database structure.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
