# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0018_annotation_point_one_to_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationtoolsettings',
            name='human_annotated_point_color',
            field=models.CharField(default='8888FF', max_length=6, verbose_name='Confirmed point color'),
        ),
        migrations.AlterField(
            model_name='annotationtoolsettings',
            name='point_marker',
            field=models.CharField(choices=[('crosshair', 'Crosshair'), ('circle', 'Circle'), ('crosshair and circle', 'Crosshair and circle'), ('box', 'Box')], default='crosshair', max_length=30),
        ),
        migrations.AlterField(
            model_name='annotationtoolsettings',
            name='robot_annotated_point_color',
            field=models.CharField(default='FFFF00', max_length=6, verbose_name='Unconfirmed point color'),
        ),
        migrations.AlterField(
            model_name='annotationtoolsettings',
            name='selected_point_color',
            field=models.CharField(default='00FF00', max_length=6),
        ),
        migrations.AlterField(
            model_name='annotationtoolsettings',
            name='unannotated_point_color',
            field=models.CharField(default='FFFF00', max_length=6, verbose_name='Not annotated point color'),
        ),
    ]
