# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-25 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0019_field_string_attributes_to_unicode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnnotationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('image', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='annoinfo', to='images.Image')),
                ('last_annotation', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='annotations.Annotation')),
            ],
        ),
    ]
