# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-25 22:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
from tqdm import tqdm


def populate_annotation_info_fields(apps, schema_editor):
    """Populate the ImageAnnotationInfo table using the Image values."""
    Image = apps.get_model('images', 'Image')
    Source = apps.get_model('images', 'Source')
    ImageAnnotationInfo = apps.get_model('annotations', 'ImageAnnotationInfo')

    # Iterate over sources, then images. We don't just flatly iterate over
    # images, because too many loop iterations (like millions) can cause
    # Python to hang indefinitely until the process is OS-killed.
    for source in tqdm(Source.objects.all(), disable=settings.TQDM_DISABLE):
        for image in Image.objects.filter(source=source):
            annotation_info = ImageAnnotationInfo(
                image=image,
                confirmed=image.confirmed,
                last_annotation=image.last_annotation,
            )
            annotation_info.save()


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0020_imageannotationinfo'),
        # Image's confirmed and last_annotation fields should be up to date.
        ('images', '0025_populate_image_last_annotation'),
    ]

    operations = [
        migrations.RunPython(
            populate_annotation_info_fields, migrations.RunPython.noop,
            elidable=True),
    ]
