# Generated by Django 4.1.10 on 2023-11-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_squashed_0021_populate_imageannotationinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageannotationinfo',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='imageannotationinfo',
            name='status',
            field=models.CharField(choices=[('unclassified', 'Unclassified'), ('unconfirmed', 'Unconfirmed'), ('confirmed', 'Confirmed')], default='unclassified', max_length=30),
        ),
    ]
