# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_add_empty_labelset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annotations.Label'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='robot_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Robot'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annotationtoolaccess',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='label',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=b'Created by'),
        ),
        migrations.AlterField(
            model_name='label',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annotations.LabelGroup', verbose_name=b'Functional Group'),
        ),
    ]
