# Generated by Django 1.11.29 on 2021-03-25 08:05
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_squashed_0033_remove_image_annotation_progress'),
        ('labels', '0001_squashed_0012_field_string_attributes_to_unicode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=False)),
                ('runtime_train', models.BigIntegerField(default=0)),
                ('nbr_train_images', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Source')),
                ('accuracy', models.FloatField(null=True)),
                ('epoch_ref_accuracy', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted', models.BooleanField(default=False)),
                ('classified', models.BooleanField(default=False)),
                ('runtime_total', models.IntegerField(null=True)),
                ('runtime_core', models.IntegerField(null=True)),
                ('extracted_date', models.DateTimeField(null=True)),
                ('model_was_cashed', models.NullBooleanField()),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.Label')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Point')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Source')),
            ],
        ),
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('PENDING', 'PENDING'), ('RUNNABLE', 'RUNNABLE'), ('STARTING', 'STARTING'), ('RUNNING', 'RUNNING'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED')], default='SUBMITTED', max_length=12)),
                ('batch_token', models.CharField(max_length=128, null=True)),
                ('job_token', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
    ]
