# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifier',
            name='version',
        ),

        migrations.RemoveField(
            model_name='classifier',
            name='path_to_model',
        ),
    ]
