# Generated by Django 2.2.20 on 2021-09-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0001_squashed_0011_features_image_non_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='status',
            field=models.CharField(choices=[('PN', 'Training pending'), ('ER', 'Training got an error'), ('RJ', "Rejected because accuracy didn't improve enough"), ('AC', 'Accepted as new classifier')], default='PN', max_length=2),
        ),
    ]
