# Generated by Django 2.2.20 on 2021-09-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0003_populate_classifier_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifier',
            name='valid',
        ),
    ]
