# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0003_features_model_was_cashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='classifier',
            name='epoch_ref_accuracy',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
