# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0005_more_classifier_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.LocalLabel'),
        ),
    ]
