# Generated by Django 2.2.20 on 2022-12-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0006_score_bigautofield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchjob',
            name='job_token',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
