# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-24 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0006_batchjob'),
    ]

    operations = [
        # Ultimately we want the name 'image' and related_name 'features', but
        # those names create conflicts with the old Image.features field.
        # So we temporarily use '_new' suffixes until we can port the values
        # over and delete the old field.
        migrations.AddField(
            model_name='features',
            name='image_new',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features_new', to='images.Image'),
        ),
    ]
