# Generated by Django 2.2.20 on 2022-12-05 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_dates_verbose_names'),
        ('vision_backend', '0007_batchjob_jobtoken_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchjob',
            name='job_token',
        ),
        migrations.AddField(
            model_name='batchjob',
            name='internal_job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'),
        ),
    ]
