# Generated by Django 2.2.20 on 2022-12-05 02:57

from django.db import migrations


def delete_old_batch_jobs(apps, schema_editor):
    """
    It's a pain to 'fabricate' Jobs for existing BatchJobs, which
    didn't have Jobs to point to in the first place.
    So we just ensure that all existing BatchJobs are completed,
    and delete them.
    """
    BatchJob = apps.get_model('vision_backend', 'BatchJob')

    if BatchJob.objects.exclude(status__in=['SUCCEEDED', 'FAILED']).exists():
        raise ValueError(
            "There are still uncompleted BatchJobs,"
            " so we can't proceed with migrations yet.")

    BatchJob.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0008_batchjob_add_internaljob'),
    ]

    operations = [
        migrations.RunPython(
            delete_old_batch_jobs,
            migrations.RunPython.noop),
    ]
