# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-24 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # Image.features field should be removed
        ('images', '0031_remove_image_features'),
        ('vision_backend', '0008_populate_features_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features', old_name='image_new', new_name='image',
        ),
        # Remove custom related_name, now that the default won't cause conflicts
        migrations.AlterField(
            model_name='features',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
