# Generated by Django 2.2.20 on 2022-12-05 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0009_batchjob_delete_old_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchjob',
            name='internal_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'),
        ),
    ]
