# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-28 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0010_features_image_null_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
