# Generated by Django 3.2.18 on 2023-04-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0010_batchjob_internaljob_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='model_was_cashed',
            field=models.BooleanField(null=True),
        ),
    ]
