# Generated by Django 3.2.18 on 2023-04-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0011_alter_features_model_was_cashed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='model_was_cashed',
            new_name='model_was_cached',
        ),
    ]
