# Generated by Django 4.1.10 on 2023-11-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0013_classifier_train_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='classified',
        ),
    ]
