# Generated by Django 4.1.10 on 2023-11-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0014_remove_features_classified'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='extractor_loaded_remotely',
            field=models.BooleanField(null=True),
        ),
    ]
