# Generated by Django 4.1.10 on 2023-11-11 01:33

from django.db import migrations


def populate_loaded_field(apps, schema_editor):
    """
    Populate extractor_loaded_remotely field as the opposite value of the
    model_was_cached field.
    """
    Features = apps.get_model('vision_backend', 'Features')

    # This can be a single QuerySet.update() in Django 4.2 with a negation
    # operator on an F expression.
    # https://code.djangoproject.com/ticket/16211
    # Features.objects.all().update(
    #     extractor_loaded_remotely=~F('model_was_cached')
    # )
    # But in the absence of that, updating per value isn't bad either.
    Features.objects.filter(
        model_was_cached=True).update(extractor_loaded_remotely=False)
    Features.objects.filter(
        model_was_cached=False).update(extractor_loaded_remotely=True)


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0015_features_extractor_loaded_remotely'),
    ]

    operations = [
        migrations.RunPython(populate_loaded_field, migrations.RunPython.noop),
    ]
