# Generated by Django 4.1.10 on 2023-11-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0016_populate_extractor_loaded_remotely'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='model_was_cached',
        ),
    ]
