# Generated by Django 4.1.10 on 2023-11-11 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0017_remove_features_model_was_cached'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='runtime_core',
        ),
    ]
