# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotations', '0009_rename_labelgroup_table'),
    ]

    # Convert "operations" to only be "state_operations"
    state_operations = [
        # These migrations were auto-generated by Django makemigrations.
        migrations.CreateModel(
            name='LabelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45)),
                ('code', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]

    operations = [
        # By running only state operations, we are making Django think it has
        # applied this migration to the database. In reality, we renamed a
        # "annotations_labelgroup" table to "labels_labelgroup" earlier.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
