# Generated by Django 2.0.13 on 2021-04-19 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_squashed_0012_field_string_attributes_to_unicode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='duplicate',
            field=models.ForeignKey(blank=True, limit_choices_to={'verified': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.Label'),
        ),
        migrations.AlterField(
            model_name='locallabel',
            name='global_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labels.Label'),
        ),
    ]
