# Generated by Django 2.2.20 on 2021-05-05 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_duplicate_limitchoices_global_ondelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='default_code',
            field=models.CharField(help_text='Up to 10 characters. Only a few types of punctuation are accepted. Note that this is just a default code; you can later customize the codes that are used in your source.', max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\ \\&\\*\\+\\-\\.\\/_]+\\Z', message='You entered disallowed characters or punctuation.')], verbose_name='Default Short Code'),
        ),
        migrations.AlterField(
            model_name='label',
            name='description',
            field=models.TextField(help_text='Please use English.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(help_text='Please use English words and names.', max_length=45, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9\\ \\&\\'\\(\\)\\+\\,\\-\\.\\/\\:\\;\\<\\>_]+\\Z", message='You entered disallowed characters or punctuation.')]),
        ),
    ]
