# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('annotations', '0015_rename_labelset_table'),
        ('labels', '0002_label'),
    ]

    # Convert "operations" to only be "state_operations"
    state_operations = [
        # These migrations were auto-generated by Django makemigrations.
        migrations.CreateModel(
            name='LabelSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=45)),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name=b'Date edited')),
                ('labels', models.ManyToManyField(to='labels.Label')),
            ],
        ),
    ]

    operations = [
        # By running only state operations, we are making Django think it has
        # applied this migration to the database. In reality, we renamed
        # the relevant database tables earlier.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
