# Generated by Django 3.2.18 on 2023-04-25 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_label_constraints_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='default_code',
            field=models.CharField(help_text='Up to 10 characters. Only a few types of punctuation are accepted. Note that this is just a default code; you can later customize the codes that are used in your source.', max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\ \\&\\*\\+\\-\\./_]+\\Z', message='You entered disallowed characters or punctuation.')], verbose_name='Default Short Code'),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(help_text='Please use English words and names.', max_length=45, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9\\ \\&'\\(\\)\\+,\\-\\./:;<>_]+\\Z", message='You entered disallowed characters or punctuation.')]),
        ),
    ]
