# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_labelset'),
        # Just in case, we'll make sure the label-related models are
        # completely moved out of the annotations app first.
        ('annotations', '0016_delete_labelset'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name=b'Short Code')),
                ('global_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.Label')),
                ('labelset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.LabelSet')),
            ],
        ),
    ]
