# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0006_label_rename_code_to_default_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='default_code',
            field=models.CharField(max_length=10, verbose_name=b'Default Short Code'),
        ),
    ]
