# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-12 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0008_remove_labelset_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'permissions': (('verify_label', 'Can change verified field'),)},
        ),
        migrations.AddField(
            model_name='label',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
