# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-12 04:14
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings
from django.core.management.sql import emit_post_migrate_signal


def create_labelset_committee_user_group(
        apps, schema_editor, with_create_permissions=True):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    group = Group(name="Labelset Committee")
    group.save()

    perms = []
    perm_codes = ['change_label', 'verify_label']
    for perm_code in perm_codes:
        try:
            perm = Permission.objects.get(
                codename=perm_code, content_type__app_label='labels')
        except Permission.DoesNotExist:
            # If this is the first round of migrations ever run since the
            # relevant permissions and content types were defined
            # (e.g. in unit tests), then permissions and content types
            # will have to be created.
            # They're normally created as part of the post-migration signal.
            # We will trigger this signal manually to create the perms/ctypes.
            # https://code.djangoproject.com/ticket/23422#comment:20

            # This particular function signature may change in some Django
            # versions, but it works in Django 1.9.5 at least.
            emit_post_migrate_signal(0, False, 'default')

            # Try getting the perm again
            perm = Permission.objects.get(
                codename=perm_code, content_type__app_label='labels')
        perms.append(perm)

    group.permissions.add(*perms)


def delete_labelset_committee_user_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group = Group.objects.get(name="Labelset Committee")
    group.delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labels', '0009_add_verified_field_and_permission'),
        # The manual call of the post-migration signal may fail
        # unless the contenttypes migrations and sites migrations
        # (if that app is used) run first.
        # https://code.djangoproject.com/ticket/23422#comment:25
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            create_labelset_committee_user_group,
            delete_labelset_committee_user_group,
        ),
    ]
