# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-07 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0010_add_labelset_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='duplicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.Label'),
        ),
    ]
