# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import labels.models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0011_label_duplicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='label',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='label',
            name='default_code',
            field=models.CharField(max_length=10, verbose_name='Default Short Code'),
        ),
        migrations.AlterField(
            model_name='label',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labels.LabelGroup', verbose_name='Functional Group'),
        ),
        migrations.AlterField(
            model_name='label',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(help_text="For best results, please use an image that's close to 150 x 150 pixels. Otherwise, we'll resize and crop your image to make sure it's that size.", null=True, upload_to=labels.models.get_label_thumbnail_upload_path, verbose_name='Example image (thumbnail)'),
        ),
        migrations.AlterField(
            model_name='labelset',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date edited'),
        ),
        migrations.AlterField(
            model_name='locallabel',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Short Code'),
        ),
    ]
