# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-10 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reporting', '0002_alter_specify_on_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
