# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_specify_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='labelset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='annotations.LabelSet'),
        ),
    ]
