# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_update_image_filepaths'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='aux1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='metadata',
            name='aux2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='metadata',
            name='aux3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='metadata',
            name='aux4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='metadata',
            name='aux5',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
