# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_port_metadata_values_to_aux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value1',
            name='source',
        ),
        migrations.RemoveField(
            model_name='value2',
            name='source',
        ),
        migrations.RemoveField(
            model_name='value3',
            name='source',
        ),
        migrations.RemoveField(
            model_name='value4',
            name='source',
        ),
        migrations.RemoveField(
            model_name='value5',
            name='source',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='value1',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='value2',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='value3',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='value4',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='value5',
        ),
        migrations.DeleteModel(
            name='Value1',
        ),
        migrations.DeleteModel(
            name='Value2',
        ),
        migrations.DeleteModel(
            name='Value3',
        ),
        migrations.DeleteModel(
            name='Value4',
        ),
        migrations.DeleteModel(
            name='Value5',
        ),
    ]
