# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_remove_metadata_value_foreignkeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='key1',
            field=models.CharField(default=b'Aux1', max_length=50, verbose_name=b'Aux. metadata 1'),
        ),
        migrations.AlterField(
            model_name='source',
            name='key2',
            field=models.CharField(default=b'Aux2', max_length=50, verbose_name=b'Aux. metadata 2'),
        ),
        migrations.AlterField(
            model_name='source',
            name='key3',
            field=models.CharField(default=b'Aux3', max_length=50, verbose_name=b'Aux. metadata 3'),
        ),
        migrations.AlterField(
            model_name='source',
            name='key4',
            field=models.CharField(default=b'Aux4', max_length=50, verbose_name=b'Aux. metadata 4'),
        ),
        migrations.AlterField(
            model_name='source',
            name='key5',
            field=models.CharField(default=b'Aux5', max_length=50, verbose_name=b'Aux. metadata 5'),
        ),
    ]
