# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 05:01
from __future__ import unicode_literals

from django.db import migrations


def set_blank_aux_names_to_default(apps, schema_editor):
    Source = apps.get_model('images', 'Source')
    sources = Source.objects.all()

    for source in sources:
        if source.key1 == "":
            source.key1 = "Aux1"
        if source.key2 == "":
            source.key2 = "Aux2"
        if source.key3 == "":
            source.key3 = "Aux3"
        if source.key4 == "":
            source.key4 = "Aux4"
        if source.key5 == "":
            source.key5 = "Aux5"
        source.save()


def dont_change_values(apps, schema_editor):
    print("\nNo action taken in this migration rollback."
          " No way to know if instances of default values were entered"
          " intentionally or were originally blank.")


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_alter_location_keys_not_blank'),
    ]

    operations = [
        migrations.RunPython(
            set_blank_aux_names_to_default, dont_change_values, elidable=True),
    ]
