# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_update_blank_aux_names_to_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, verbose_name=b'Comments'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Name'),
        ),
    ]
