# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 02:31
from __future__ import unicode_literals
import posixpath

from django.db import migrations


def rename_dupe_image_names(apps, schema_editor):
    """
    If multiple images in a source share the same name, add name suffixes
    to each of those images so that (1) they end up having different names,
    and (2) the source owner can more easily find the dupe names.
    """
    format_str = '{original_name}__dupe-name-{number:02d}{extension}'

    Source = apps.get_model('images', 'Source')
    Metadata = apps.get_model('images', 'Metadata')
    for source in Source.objects.all():
        metadatas = Metadata.objects.filter(image__source=source)
        names = list(
            metadatas.values_list('name', flat=True)
        )
        dupe_names = set(
            name for name in names
            if names.count(name) > 1
        )
        for name in dupe_names:
            dupe_metadatas = metadatas.filter(name=name)

            original_name_without_ext, extension = posixpath.splitext(name)

            for number, metadata in enumerate(dupe_metadatas, 1):
                metadata.name = format_str.format(
                    original_name=original_name_without_ext,
                    number=number,
                    extension=extension,
                )
                metadata.save()


def remove_dupe_name_suffixes(apps, schema_editor):
    """
    If a dupe-name suffix is found in an image name, remove that suffix.
    """
    Metadata = apps.get_model('images', 'Metadata')
    metadatas = Metadata.objects.filter(name__contains='__dupe-name-')
    for metadata in metadatas:
        current_name_without_ext, extension = posixpath.splitext(metadata.name)
        # Cut off the part from __dupe-name- and after
        reverted_name_without_ext = current_name_without_ext[
            :current_name_without_ext.index('__dupe-name-')]
        reverted_name = reverted_name_without_ext + extension
        metadata.name = reverted_name
        metadata.save()


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_alter_name_comments_verbose_names'),
    ]

    operations = [
        migrations.RunPython(
            rename_dupe_image_names, remove_dupe_name_suffixes, elidable=True),
    ]
