# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_rename_dupe_image_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagestatus',
            name='featureFileHasHumanLabels',
        ),
        migrations.RemoveField(
            model_name='imagestatus',
            name='preprocessed',
        ),
        migrations.AddField(
            model_name='imagestatus',
            name='featuresSubmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='point',
            name='features_extracted',
            field=models.BooleanField(default=False),
        ),
    ]
