# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def initialize_features_for_images(apps, schema_editor):
    Image = apps.get_model("images", "Image")
    Features = apps.get_model("vision_backend", "Features")
    for image in Image.objects.filter():
        if not image.features:
            feat = Features()
            feat.save()
            image.features = feat
            image.save()

def initialize_features_for_images_backwards(apps, schema_editor):
    # no need to roll back these changes.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_remove_vision_backend_fields'),
    ]

    operations = [
    	
        # Add the field allowing nulls
    	migrations.AddField(
            model_name='image',
            name='features',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='vision_backend.Features'),
        ),

        # Populate all nulls
        migrations.RunPython(initialize_features_for_images, initialize_features_for_images_backwards),
		
        # Now, dis-allow nulls
        migrations.AlterField(
            model_name='image',
            name='features',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='vision_backend.Features'),
        ),

    ]
