# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_add_features_foreignkey'),
        ('labels', '0003_labelset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='labelset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='labels.LabelSet'),
        ),
    ]
