# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-01 12:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_remove_imagestatus_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='confidence_threshold',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name=b'Confidence threshold (%)'),
        ),
    ]
