# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-04 20:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_remove_source_alleviate_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='image_height_in_cm',
        ),
        migrations.AlterField(
            model_name='metadata',
            name='height_in_cm',
            field=models.IntegerField(blank=True, help_text=b'The number of centimeters of substrate the image covers, from the top of the image to the bottom.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Height (cm)'),
        ),
        migrations.AlterField(
            model_name='source',
            name='image_annotation_area',
            field=models.CharField(help_text=b"This defines a rectangle of the image where annotation points are allowed to be generated.\nFor example, X boundaries of 10% and 95% mean that the leftmost 10% and the rightmost 5% of the image will not have any points. Decimals like 95.6% are allowed.\nLater, you can also set these boundaries as pixel counts on a per-image basis; for images that don't have a specific value set, these percentages will be used.", max_length=50, null=True, verbose_name=b'Default image annotation area'),
        ),
    ]
