# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-01-14 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_remove_source_cm_height_and_other_alterations'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cpc_content',
            field=models.TextField(default=b'', verbose_name=b'File content of last .cpc uploaded for this image'),
        ),
        migrations.AddField(
            model_name='source',
            name='cpce_code_filepath',
            field=models.CharField(default=b'', max_length=1000, verbose_name=b'Local absolute path to the CPCe code file'),
        ),
        migrations.AddField(
            model_name='source',
            name='cpce_image_dir',
            field=models.CharField(default=b'', help_text=b'Ending slash can be present or not', max_length=1000, verbose_name=b'Local absolute path to the directory with image files'),
        ),
    ]
