# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-01-15 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0020_add_cpc_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cpc_filename',
            field=models.CharField(default=b'', max_length=1000, verbose_name=b'Filename of last .cpc uploaded for this image'),
        ),
    ]
