# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-18 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0021_image_cpc_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='enable_robot_classifier',
            field=models.BooleanField(default=True, help_text=b"With this option on, the automatic classification system will go through your images and add unconfirmed annotations to them. Then when you enter the annotation tool, you will be able to start from the system's suggestions instead of from a blank slate.", verbose_name=b'Enable robot classifier'),
        ),
        migrations.AlterField(
            model_name='source',
            name='visibility',
            field=models.CharField(choices=[(b'b', b'Public'), (b'v', b'Private')], default=b'b', max_length=1),
        ),
    ]
