# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-18 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0018_annotation_point_one_to_one'),
        ('images', '0023_point_rowcol_zero_indexing'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='last_annotation',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='annotations.Annotation'),
        ),
    ]
