# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-18 04:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
from tqdm import tqdm


def populate_last_annotation_field(apps, schema_editor):
    """
    Populate all images' last_annotation foreign key fields.
    This can take a long time.
    """
    Source = apps.get_model('images', 'Source')

    for source in tqdm(Source.objects.all(), disable=settings.TQDM_DISABLE):
        for image in source.image_set.all():
            last_annotation = \
                image.annotation_set.order_by('-annotation_date').first()
            # If there are no annotations, then first() returns None.
            if last_annotation:
                image.last_annotation = last_annotation
                image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0024_image_last_annotation'),
    ]

    operations = [
        migrations.RunPython(
            populate_last_annotation_field, migrations.RunPython.noop),
    ]
