# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 18:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import easy_thumbnails.fields
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0025_populate_image_last_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cpc_content',
            field=models.TextField(default='', verbose_name='File content of last .cpc uploaded for this image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='cpc_filename',
            field=models.CharField(default='', max_length=1000, verbose_name='Filename of last .cpc uploaded for this image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_file',
            field=easy_thumbnails.fields.ThumbnailerImageField(height_field='original_height', upload_to=images.models.get_original_image_upload_path, width_field='original_width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='point_generation_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='How points were generated'),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='annotation_area',
            field=models.CharField(blank=True, help_text='This defines a rectangle of the image where annotation points are allowed to be generated. If you change this, then new points will be generated for this image, and the old points will be deleted.', max_length=50, null=True, verbose_name='Annotation area'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='balance',
            field=models.CharField(blank=True, max_length=200, verbose_name='White balance card'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='camera',
            field=models.CharField(blank=True, max_length=200, verbose_name='Camera'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='depth',
            field=models.CharField(blank=True, max_length=45, verbose_name='Depth'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='framing',
            field=models.CharField(blank=True, max_length=200, verbose_name='Framing gear used'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='height_in_cm',
            field=models.IntegerField(blank=True, help_text='The number of centimeters of substrate the image covers, from the top of the image to the bottom.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='photo_date',
            field=models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='photographer',
            field=models.CharField(blank=True, max_length=45, verbose_name='Photographer'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='strobes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Strobes'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='water_quality',
            field=models.CharField(blank=True, max_length=45, verbose_name='Water quality'),
        ),
        migrations.AlterField(
            model_name='source',
            name='confidence_threshold',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Confidence threshold (%)'),
        ),
        migrations.AlterField(
            model_name='source',
            name='cpce_code_filepath',
            field=models.CharField(default='', max_length=1000, verbose_name='Local absolute path to the CPCe code file'),
        ),
        migrations.AlterField(
            model_name='source',
            name='cpce_image_dir',
            field=models.CharField(default='', help_text='Ending slash can be present or not', max_length=1000, verbose_name='Local absolute path to the directory with image files'),
        ),
        migrations.AlterField(
            model_name='source',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='source',
            name='default_point_generation_method',
            field=models.CharField(default='m_200', help_text="When we create annotation points for uploaded images, this is how we'll generate the point locations. Note that if you change this setting later on, it will NOT apply to images that are already uploaded.", max_length=50, verbose_name='Point generation method'),
        ),
        migrations.AlterField(
            model_name='source',
            name='enable_robot_classifier',
            field=models.BooleanField(default=True, help_text="With this option on, the automatic classification system will go through your images and add unconfirmed annotations to them. Then when you enter the annotation tool, you will be able to start from the system's suggestions instead of from a blank slate.", verbose_name='Enable robot classifier'),
        ),
        migrations.AlterField(
            model_name='source',
            name='image_annotation_area',
            field=models.CharField(help_text="This defines a rectangle of the image where annotation points are allowed to be generated.\nFor example, X boundaries of 10% and 95% mean that the leftmost 10% and the rightmost 5% of the image will not have any points. Decimals like 95.6% are allowed.\nLater, you can also set these boundaries as pixel counts on a per-image basis; for images that don't have a specific value set, these percentages will be used.", max_length=50, null=True, verbose_name='Default image annotation area'),
        ),
        migrations.AlterField(
            model_name='source',
            name='key1',
            field=models.CharField(default='Aux1', max_length=50, verbose_name='Aux. metadata 1'),
        ),
        migrations.AlterField(
            model_name='source',
            name='key2',
            field=models.CharField(default='Aux2', max_length=50, verbose_name='Aux. metadata 2'),
        ),
        migrations.AlterField(
            model_name='source',
            name='key3',
            field=models.CharField(default='Aux3', max_length=50, verbose_name='Aux. metadata 3'),
        ),
        migrations.AlterField(
            model_name='source',
            name='key4',
            field=models.CharField(default='Aux4', max_length=50, verbose_name='Aux. metadata 4'),
        ),
        migrations.AlterField(
            model_name='source',
            name='key5',
            field=models.CharField(default='Aux5', max_length=50, verbose_name='Aux. metadata 5'),
        ),
        migrations.AlterField(
            model_name='source',
            name='visibility',
            field=models.CharField(choices=[('b', 'Public'), ('v', 'Private')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='sourceinvite',
            name='source_perm',
            field=models.CharField(choices=[('source_view', 'View'), ('source_edit', 'Edit'), ('source_admin', 'Admin')], max_length=50),
        ),
    ]
