# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-19 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0026_field_string_attributes_to_unicode'),
    ]

    # By specifying a default value here in AddField(), that value is given to
    # all existing sources.
    operations = [
        migrations.AddField(
            model_name='source',
            name='feature_extractor_setting',
            field=models.CharField(choices=[('efficientnet_b0_ver1', 'EfficientNet (default)'), ('vgg16_coralnet_ver1', 'VGG16 (legacy)')], default='vgg16_coralnet_ver1', max_length=50, verbose_name='Feature extractor'),
        ),
    ]
