# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-19 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0027_source_feature_extractor_setting'),
    ]

    # By changing the default value here in AlterField(), that value becomes
    # the default for any sources created from now on.
    operations = [
        migrations.AlterField(
            model_name='source',
            name='feature_extractor_setting',
            field=models.CharField(choices=[('efficientnet_b0_ver1', 'EfficientNet (default)'), ('vgg16_coralnet_ver1', 'VGG16 (legacy)')], default='efficientnet_b0_ver1', max_length=50, verbose_name='Feature extractor'),
        ),
    ]
