# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-28 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0028_change_default_extractor'),
    ]

    operations = [
        # To remove this field while making the migration process reversible,
        # we'll make the field nullable, then write a backwards migration to
        # populate the field, then remove the field. This is step 1.
        migrations.AlterField(
            model_name='image',
            name='features',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='vision_backend.Features'),
        ),
    ]
