# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 00:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
from tqdm import tqdm


def populate_image_fields(apps, schema_editor):
    """
    Populate the Image model's fields using the ImageAnnotationInfo values.
    """
    Image = apps.get_model('images', 'Image')
    Source = apps.get_model('images', 'Source')

    # Iterate over sources, then images. We don't just flatly iterate over
    # images, because too many loop iterations (like millions) can cause
    # Python to hang indefinitely until the process is OS-killed.
    for source in tqdm(Source.objects.all(), disable=settings.TQDM_DISABLE):
        for image in Image.objects.filter(source=source):
            image.confirmed = image.annoinfo.confirmed
            image.last_annotation = image.annoinfo.last_annotation
            image.save()


class Migration(migrations.Migration):

    dependencies = [
        # ('annotations', '0021_populate_imageannotationinfo'),
        ('images', '0031_remove_image_features'),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, populate_image_fields,
            elidable=True),
    ]
