# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-25 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0032_reverse_populate_image_annotation_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='image',
            name='last_annotation',
        ),
    ]
