name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    # ubuntu-22.04 doesn't have Python 3.6 available, so we pin to 20.04
    # until we can update Python.
    # https://github.com/actions/setup-python/issues/162
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6]
    env:
      DJANGO_SETTINGS_MODULE: config.settings.ci

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/production.txt
    - name: Make Directories
      run: |
        mkdir ../log
        mkdir ../tmp
    - name: Run Tests
      run: |
        python manage.py test
      working-directory: ./project
      env:
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
